[versions]
# libraries

# plugins
kotlin = "2.1.0"
changelog = "2.2.1"
gradleIntelliJPlugin = "2.2.0"
qodana = "2024.2.6"
kover = "0.8.3"

[libraries]
json-pathkt = "com.nfeld.jsonpathkt:jsonpathkt:2.0.1"

okhttp = "com.squareup.okhttp3:okhttp:4.4.1"
okhttp-sse = "com.squareup.okhttp3:okhttp-sse:4.12.0"
kaml = "com.charleskorn.kaml:kaml:0.66.0"

# org.reflections:reflections:0.10.2
reflections = "org.reflections:reflections:0.10.2"
# "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3"
serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3"

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }